// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.4
// source: services.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	InfoService_GetSellGoods_FullMethodName = "/api.InfoService/GetSellGoods"
	InfoService_GetBuyGoods_FullMethodName  = "/api.InfoService/GetBuyGoods"
	InfoService_GetStations_FullMethodName  = "/api.InfoService/GetStations"
)

// InfoServiceClient is the client API for InfoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type InfoServiceClient interface {
	GetSellGoods(ctx context.Context, in *GetSellGoodsRequest, opts ...grpc.CallOption) (*GetSellGoodsResponse, error)
	GetBuyGoods(ctx context.Context, in *GetBuyGoodsRequest, opts ...grpc.CallOption) (*GetBuyGoodsResponse, error)
	GetStations(ctx context.Context, in *GetStationsRequest, opts ...grpc.CallOption) (*GetStationsResponse, error)
}

type infoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInfoServiceClient(cc grpc.ClientConnInterface) InfoServiceClient {
	return &infoServiceClient{cc}
}

func (c *infoServiceClient) GetSellGoods(ctx context.Context, in *GetSellGoodsRequest, opts ...grpc.CallOption) (*GetSellGoodsResponse, error) {
	out := new(GetSellGoodsResponse)
	err := c.cc.Invoke(ctx, InfoService_GetSellGoods_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infoServiceClient) GetBuyGoods(ctx context.Context, in *GetBuyGoodsRequest, opts ...grpc.CallOption) (*GetBuyGoodsResponse, error) {
	out := new(GetBuyGoodsResponse)
	err := c.cc.Invoke(ctx, InfoService_GetBuyGoods_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *infoServiceClient) GetStations(ctx context.Context, in *GetStationsRequest, opts ...grpc.CallOption) (*GetStationsResponse, error) {
	out := new(GetStationsResponse)
	err := c.cc.Invoke(ctx, InfoService_GetStations_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InfoServiceServer is the server API for InfoService service.
// All implementations must embed UnimplementedInfoServiceServer
// for forward compatibility
type InfoServiceServer interface {
	GetSellGoods(context.Context, *GetSellGoodsRequest) (*GetSellGoodsResponse, error)
	GetBuyGoods(context.Context, *GetBuyGoodsRequest) (*GetBuyGoodsResponse, error)
	GetStations(context.Context, *GetStationsRequest) (*GetStationsResponse, error)
	mustEmbedUnimplementedInfoServiceServer()
}

// UnimplementedInfoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedInfoServiceServer struct {
}

func (UnimplementedInfoServiceServer) GetSellGoods(context.Context, *GetSellGoodsRequest) (*GetSellGoodsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSellGoods not implemented")
}
func (UnimplementedInfoServiceServer) GetBuyGoods(context.Context, *GetBuyGoodsRequest) (*GetBuyGoodsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBuyGoods not implemented")
}
func (UnimplementedInfoServiceServer) GetStations(context.Context, *GetStationsRequest) (*GetStationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStations not implemented")
}
func (UnimplementedInfoServiceServer) mustEmbedUnimplementedInfoServiceServer() {}

// UnsafeInfoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InfoServiceServer will
// result in compilation errors.
type UnsafeInfoServiceServer interface {
	mustEmbedUnimplementedInfoServiceServer()
}

func RegisterInfoServiceServer(s grpc.ServiceRegistrar, srv InfoServiceServer) {
	s.RegisterService(&InfoService_ServiceDesc, srv)
}

func _InfoService_GetSellGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSellGoodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServiceServer).GetSellGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InfoService_GetSellGoods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServiceServer).GetSellGoods(ctx, req.(*GetSellGoodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InfoService_GetBuyGoods_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBuyGoodsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServiceServer).GetBuyGoods(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InfoService_GetBuyGoods_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServiceServer).GetBuyGoods(ctx, req.(*GetBuyGoodsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _InfoService_GetStations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InfoServiceServer).GetStations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InfoService_GetStations_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InfoServiceServer).GetStations(ctx, req.(*GetStationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// InfoService_ServiceDesc is the grpc.ServiceDesc for InfoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InfoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.InfoService",
	HandlerType: (*InfoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSellGoods",
			Handler:    _InfoService_GetSellGoods_Handler,
		},
		{
			MethodName: "GetBuyGoods",
			Handler:    _InfoService_GetBuyGoods_Handler,
		},
		{
			MethodName: "GetStations",
			Handler:    _InfoService_GetStations_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services.proto",
}
