apiVersion: apps/v1
kind: Deployment
metadata:
  name: calculate
  labels:
    app: calculate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: calculate
  template:
    metadata:
      labels:
        app: calculate
    spec:
      containers:
      - name: calculate
        image: ghcr.io/kud-00/resonance/calculate:main
        imagePullPolicy: Always
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: calculate
spec:
  selector:
    app: calculate
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
